# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twirp/foos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='twirp/foos.proto',
  package='foos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10twirp/foos.proto\x12\x04\x66oos\"0\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\"\x06\n\x04Game\"!\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.foos.User\"\x11\n\x0fGetUsersRequest\"-\n\x10GetUsersResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.foos.User\"`\n\x10InputGameRequest\x12\x0f\n\x07winners\x18\x01 \x03(\t\x12\x0e\n\x06losers\x18\x02 \x03(\t\x12\x15\n\rwinning_score\x18\x03 \x01(\x05\x12\x14\n\x0closing_score\x18\x04 \x01(\x05\"\x13\n\x11InputGameResponse\")\n\x16GetGamesForUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"4\n\x17GetGamesForUserResponse\x12\x19\n\x05games\x18\x01 \x03(\x0b\x32\n.foos.Game2\x90\x02\n\x04\x46oos\x12?\n\nCreateUser\x12\x17.foos.CreateUserRequest\x1a\x18.foos.CreateUserResponse\x12\x39\n\x08GetUsers\x12\x15.foos.GetUsersRequest\x1a\x16.foos.GetUsersResponse\x12<\n\tInputGame\x12\x16.foos.InputGameRequest\x1a\x17.foos.InputGameResponse\x12N\n\x0fGetGamesForUser\x12\x1c.foos.GetGamesForUserRequest\x1a\x1d.foos.GetGamesForUserResponseb\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='foos.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='foos.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='foos.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='foos.User.rating', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=74,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='foos.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=82,
)


_CREATEUSERREQUEST = _descriptor.Descriptor(
  name='CreateUserRequest',
  full_name='foos.CreateUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='foos.CreateUserRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=117,
)


_CREATEUSERRESPONSE = _descriptor.Descriptor(
  name='CreateUserResponse',
  full_name='foos.CreateUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='foos.CreateUserResponse.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=165,
)


_GETUSERSREQUEST = _descriptor.Descriptor(
  name='GetUsersRequest',
  full_name='foos.GetUsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=184,
)


_GETUSERSRESPONSE = _descriptor.Descriptor(
  name='GetUsersResponse',
  full_name='foos.GetUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='foos.GetUsersResponse.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=231,
)


_INPUTGAMEREQUEST = _descriptor.Descriptor(
  name='InputGameRequest',
  full_name='foos.InputGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='winners', full_name='foos.InputGameRequest.winners', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='losers', full_name='foos.InputGameRequest.losers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winning_score', full_name='foos.InputGameRequest.winning_score', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='losing_score', full_name='foos.InputGameRequest.losing_score', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=329,
)


_INPUTGAMERESPONSE = _descriptor.Descriptor(
  name='InputGameResponse',
  full_name='foos.InputGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=350,
)


_GETGAMESFORUSERREQUEST = _descriptor.Descriptor(
  name='GetGamesForUserRequest',
  full_name='foos.GetGamesForUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='foos.GetGamesForUserRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=393,
)


_GETGAMESFORUSERRESPONSE = _descriptor.Descriptor(
  name='GetGamesForUserResponse',
  full_name='foos.GetGamesForUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='games', full_name='foos.GetGamesForUserResponse.games', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=447,
)

_CREATEUSERRESPONSE.fields_by_name['user'].message_type = _USER
_GETUSERSRESPONSE.fields_by_name['users'].message_type = _USER
_GETGAMESFORUSERRESPONSE.fields_by_name['games'].message_type = _GAME
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.message_types_by_name['CreateUserRequest'] = _CREATEUSERREQUEST
DESCRIPTOR.message_types_by_name['CreateUserResponse'] = _CREATEUSERRESPONSE
DESCRIPTOR.message_types_by_name['GetUsersRequest'] = _GETUSERSREQUEST
DESCRIPTOR.message_types_by_name['GetUsersResponse'] = _GETUSERSRESPONSE
DESCRIPTOR.message_types_by_name['InputGameRequest'] = _INPUTGAMEREQUEST
DESCRIPTOR.message_types_by_name['InputGameResponse'] = _INPUTGAMERESPONSE
DESCRIPTOR.message_types_by_name['GetGamesForUserRequest'] = _GETGAMESFORUSERREQUEST
DESCRIPTOR.message_types_by_name['GetGamesForUserResponse'] = _GETGAMESFORUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.User)
  ))
_sym_db.RegisterMessage(User)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), dict(
  DESCRIPTOR = _GAME,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.Game)
  ))
_sym_db.RegisterMessage(Game)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEUSERREQUEST,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.CreateUserRequest)
  ))
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEUSERRESPONSE,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.CreateUserResponse)
  ))
_sym_db.RegisterMessage(CreateUserResponse)

GetUsersRequest = _reflection.GeneratedProtocolMessageType('GetUsersRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERSREQUEST,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.GetUsersRequest)
  ))
_sym_db.RegisterMessage(GetUsersRequest)

GetUsersResponse = _reflection.GeneratedProtocolMessageType('GetUsersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERSRESPONSE,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.GetUsersResponse)
  ))
_sym_db.RegisterMessage(GetUsersResponse)

InputGameRequest = _reflection.GeneratedProtocolMessageType('InputGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _INPUTGAMEREQUEST,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.InputGameRequest)
  ))
_sym_db.RegisterMessage(InputGameRequest)

InputGameResponse = _reflection.GeneratedProtocolMessageType('InputGameResponse', (_message.Message,), dict(
  DESCRIPTOR = _INPUTGAMERESPONSE,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.InputGameResponse)
  ))
_sym_db.RegisterMessage(InputGameResponse)

GetGamesForUserRequest = _reflection.GeneratedProtocolMessageType('GetGamesForUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETGAMESFORUSERREQUEST,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.GetGamesForUserRequest)
  ))
_sym_db.RegisterMessage(GetGamesForUserRequest)

GetGamesForUserResponse = _reflection.GeneratedProtocolMessageType('GetGamesForUserResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETGAMESFORUSERRESPONSE,
  __module__ = 'twirp.foos_pb2'
  # @@protoc_insertion_point(class_scope:foos.GetGamesForUserResponse)
  ))
_sym_db.RegisterMessage(GetGamesForUserResponse)



_FOOS = _descriptor.ServiceDescriptor(
  name='Foos',
  full_name='foos.Foos',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=450,
  serialized_end=722,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='foos.Foos.CreateUser',
    index=0,
    containing_service=None,
    input_type=_CREATEUSERREQUEST,
    output_type=_CREATEUSERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='foos.Foos.GetUsers',
    index=1,
    containing_service=None,
    input_type=_GETUSERSREQUEST,
    output_type=_GETUSERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InputGame',
    full_name='foos.Foos.InputGame',
    index=2,
    containing_service=None,
    input_type=_INPUTGAMEREQUEST,
    output_type=_INPUTGAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGamesForUser',
    full_name='foos.Foos.GetGamesForUser',
    index=3,
    containing_service=None,
    input_type=_GETGAMESFORUSERREQUEST,
    output_type=_GETGAMESFORUSERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOS)

DESCRIPTOR.services_by_name['Foos'] = _FOOS

# @@protoc_insertion_point(module_scope)
